#!/usr/bin/env python3
"""Generate a Kaggle kernel directory for a run derived from `kaggle/tpu_h1jax_cpt/run.py`.

Kaggle script kernels cannot receive environment variables, and each kernel directory must be self
contained, so derived runs (cooled leaves branched from a trunk checkpoint, replicate seeds, learning-rate
arms) are generated from the single CPT source by rewriting its `HGHOST_CPT_*` defaults. The generated
`run.py` is byte-identical to the source except for those default strings, and the kernel metadata attaches
the trunk kernel's output as a kernel source when a branch is requested.

Example (a leaf cooled from the epoch-1 checkpoint of the trunk run):

    python3 kaggle/make_leaf_kernel.py \\
      --name leaf-e1-decay10 \\
      --set RUN_NAME=leaf-e1-decay10 \\
      --set BRANCH_FROM='/kaggle/input/**/trunk-wsd-lr1e-4-seed0/tokens-000374405212/trainer_state.json' \\
      --set TOTAL_TOKENS=411845733 --set DECAY_TOKENS=37440521 --set SAVE_TOKENS= \\
      --kernel-source emberian64/h-ghost-h1jax-cpt-91m
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "tpu_h1jax_cpt" / "run.py"
SOURCE_METADATA = ROOT / "tpu_h1jax_cpt" / "kernel-metadata.json"


def rewrite_default(source: str, key: str, value: str) -> str:
    pattern = re.compile(
        r'(os\.environ\.get\(\s*"HGHOST_CPT_' + re.escape(key) + r'",\s*)"[^"]*"'
    )
    new, count = pattern.subn(lambda m: f'{m.group(1)}"{value}"', source)
    if count != 1:
        raise SystemExit(
            f"expected exactly one default for HGHOST_CPT_{key}, found {count}"
        )
    return new


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--name", required=True, help="kernel directory suffix and slug suffix"
    )
    parser.add_argument(
        "--set",
        action="append",
        default=[],
        metavar="KEY=VALUE",
        help="HGHOST_CPT_<KEY> default",
    )
    parser.add_argument(
        "--kernel-source",
        action="append",
        default=[],
        help="Kaggle kernel slug to attach",
    )
    parser.add_argument("--title", default=None)
    parser.add_argument(
        "--dataset-source",
        action="append",
        default=None,
        help="replace the dataset_sources list (repeatable)",
    )
    args = parser.parse_args()

    source = SOURCE.read_text()
    for item in args.set:
        key, _, value = item.partition("=")
        source = rewrite_default(source, key.strip(), value)
    metadata = json.loads(SOURCE_METADATA.read_text())
    slug = f"h-ghost-h1jax-{args.name}"
    metadata["id"] = f"emberian64/{slug}"
    metadata["title"] = args.title or f"H Ghost h1jax {args.name}"
    metadata["kernel_sources"] = list(args.kernel_source)
    if args.dataset_source:
        metadata["dataset_sources"] = list(args.dataset_source)

    target = ROOT / f"tpu_h1jax_{args.name.replace('-', '_')}"
    target.mkdir(parents=True, exist_ok=True)
    (target / "run.py").write_text(source)
    (target / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2) + "\n")
    shutil.copy2(ROOT / "tpu_h1jax_cpt" / "README.md", target / "README.md")
    (target / "GENERATED.md").write_text(
        "Generated by `kaggle/make_leaf_kernel.py` from `kaggle/tpu_h1jax_cpt/run.py`; do not edit by hand.\n"
        f"Settings: {args.set}\nKernel sources: {args.kernel_source}\n"
    )
    print(target)
    print(
        f"push: uvx --from kaggle kaggle kernels push -p {target.relative_to(ROOT.parent)}"
    )


if __name__ == "__main__":
    main()
