#!/usr/bin/env python3
"""Declare a Kaggle TPU run as a spec and generate its kernel directory under `kaggle/runs/<name>/`.

One kernel, many specs: the training and gate kernels live in the `hghost_jax` wheel
(`h1jax.kernels.cpt.main(spec)`, `h1jax.kernels.gate.main(spec)`); a Kaggle script kernel pushes exactly
one code file, so the per-run artifact is a small `run.py` that installs the wheel from the attached code
dataset, holds the spec as a JSON literal, and calls the kernel. The generated directory also carries the
same spec as `spec.json` (what a `kaggle/TPU_LEDGER.md` row references) and `kernel-metadata.json`.

Keys are the old `HGHOST_CPT_*` / `HGHOST_GATE_*` setting names without the prefix (case-insensitive here;
the spec stores them lower-cased); values are parsed exactly as the env kernels parsed them and stored
typed. Unknown keys fail here, before anything is pushed. Defaults live in
`jax_training/h1jax/kernels/common.py`; a spec records only what differs from them.

Example (a second epoch cooled from the epoch-1 checkpoint of the 0.5B room run):

    python3 kaggle/spec_kernel.py --name room05b-e2-v6 --kind cpt \\
      --set RUN_NAME=room05b-e2-v6-decay10 --set SSD=v2 --set PER_CHIP=16 --set LR=1e-4 \\
      --set BRANCH_FROM='/kaggle/input/**/room05b-e1-decay10/tokens-000375783424/trainer_state.json' \\
      --set TOTAL_TOKENS=794693880 --set DECAY_TOKENS=41891045 --set SAVE_TOKENS=752802835 \\
      --set MAX_MINUTES=120 --set EXTRA_VALIDATION=room-validation.bin \\
      --kernel-source emberian64/h-ghost-h1jax-room05b-e1 \\
      --dataset-source emberian64/hghost-jax-code-public \\
      --dataset-source emberian64/hghost-falcon-h1-0-5b-base-public \\
      --dataset-source emberian64/hghost-curated-tokens-v1-4-room
"""

from __future__ import annotations

import argparse
import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parent
COMMON = REPO / "jax_training" / "h1jax" / "kernels" / "common.py"
# Metadata templates: the last env-configured kernel of each kind (accelerator, privacy, dataset list).
TEMPLATE_METADATA = {
    "cpt": ROOT / "tpu_h1jax_cpt" / "kernel-metadata.json",
    "gate": ROOT / "tpu_h1jax_profile_gate_15b_deep" / "kernel-metadata.json",
}
CODE_DATASET = "emberian64/hghost-jax-code-public"

RUN_TEMPLATE = '''"""{slug}: h ghost h1jax {kind} run. Generated by kaggle/spec_kernel.py; do not edit by hand.

The kernel is h1jax.kernels.{kind}.main in the hghost_jax wheel (>= 0.2.0) attached through the code
dataset; this file installs the wheel and hands it the spec below (kept byte-identical in spec.json).
"""

import glob
import json
import os
import subprocess
import sys

SPEC = json.loads(r"""
{spec_json}
""")

LOCAL = os.environ.get("HGHOST_LOCAL") == "1" or SPEC.get("local") in (True, 1, "1")
if not LOCAL:
    wheels = [p for p in glob.glob("/kaggle/input/**/hghost_jax-*.whl", recursive=True) if os.path.isfile(p)]
    if len(wheels) != 1:
        raise RuntimeError(f"Expected exactly one hghost_jax wheel under /kaggle/input, found: {{wheels}}")
    subprocess.run([sys.executable, "-m", "pip", "install", "--no-deps", "--quiet", wheels[0]], check=True)
    print(json.dumps({{"event": "wheel", "path": wheels[0]}}), flush=True)
    os.environ.setdefault("JAX_COMPILATION_CACHE_DIR", "/kaggle/working/jax-cache")
{prelude}
from h1jax.kernels.{kind} import main

main(SPEC)
'''

# h1jax.model reads these at ITS import, which the kernel import triggers, so they are set here from the spec.
CPT_PRELUDE = '''# h1jax reads its SSD implementation and rematerialization policy from the environment at import.
os.environ.setdefault("H1JAX_SSD", str(SPEC.get("ssd", "v1")))
if SPEC.get("remat_policy"):
    os.environ.setdefault("H1JAX_REMAT_POLICY", str(SPEC["remat_policy"]))
'''
PRELUDES = {"cpt": CPT_PRELUDE, "gate": ""}


def load_common():
    """The kernels' settings tables, loaded by path so no JAX environment is needed here."""
    module_spec = importlib.util.spec_from_file_location("h1jax_kernels_common", COMMON)
    module = importlib.util.module_from_spec(module_spec)
    module_spec.loader.exec_module(module)
    return module


def build_spec(kind: str, assignments: list[str], common) -> dict:
    table = common.SETTINGS[kind]
    spec: dict = {"kind": kind}
    for item in assignments:
        key, sep, value = item.partition("=")
        key = key.strip().lower()
        if not sep:
            raise SystemExit(f"--set expects KEY=VALUE, got {item!r}")
        if key not in table:
            raise SystemExit(f"unknown {kind} setting {key!r}; known: {', '.join(sorted(table))}")
        value_kind, _ = table[key]
        try:
            spec[key] = common.coerce(value_kind, value)
        except ValueError as exc:
            raise SystemExit(f"{key}={value!r} is not a valid {value_kind}: {exc}") from exc
    return spec


def format_spec(spec: dict) -> str:
    """JSON, one key per line, lists inline: the same text goes into spec.json and the run.py literal."""
    lines = [f"  {json.dumps(key)}: {json.dumps(value)}" for key, value in spec.items()]
    return "{\n" + ",\n".join(lines) + "\n}"


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--name", required=True, help="run directory name and kernel slug suffix (hyphenated, no spaces)"
    )
    parser.add_argument("--kind", choices=sorted(TEMPLATE_METADATA), default="cpt")
    parser.add_argument(
        "--set",
        action="append",
        default=[],
        metavar="KEY=VALUE",
        help="a kernel setting (the old HGHOST_CPT_<KEY> / HGHOST_GATE_<KEY> name without the prefix)",
    )
    parser.add_argument(
        "--kernel-source",
        action="append",
        default=[],
        help="Kaggle kernel slug to attach (a previous run's output, for a branch or a resume)",
    )
    parser.add_argument("--title", default=None)
    parser.add_argument(
        "--private",
        action="store_true",
        help="is_private true in kernel-metadata.json (the template's value otherwise)",
    )
    parser.add_argument(
        "--dataset-source",
        action="append",
        default=None,
        help="replace the dataset_sources list (repeatable; must include the code dataset)",
    )
    parser.add_argument(
        "--runs-dir",
        type=Path,
        default=ROOT / "runs",
        help="where <name>/ is written (default kaggle/runs; a scratch directory for rehearsals)",
    )
    args = parser.parse_args()

    common = load_common()
    spec = build_spec(args.kind, args.set, common)
    common.resolve(spec, args.kind)  # the kernel's own validation, applied before anything is written

    metadata = json.loads(TEMPLATE_METADATA[args.kind].read_text())
    slug = f"h-ghost-h1jax-{args.name}"
    metadata["id"] = f"emberian64/{slug}"
    # Kaggle derives the kernel slug from the TITLE on first push, ignoring the metadata id, so the
    # title must slugify to the id: keep it "H Ghost h1jax <name>" (names are hyphenated, no spaces).
    metadata["title"] = f"H Ghost h1jax {args.name}"
    if args.title:
        print(
            f"note: --title ignored ({args.title!r}); Kaggle slugs come from the title"
        )
    metadata["kernel_sources"] = list(args.kernel_source)
    if args.private:
        metadata["is_private"] = True
    if args.dataset_source:
        metadata["dataset_sources"] = list(args.dataset_source)
    if CODE_DATASET not in metadata["dataset_sources"]:
        raise SystemExit(f"dataset_sources must include the code dataset {CODE_DATASET} (it carries the wheel)")

    spec_json = format_spec(spec)
    target = args.runs_dir / args.name
    target.mkdir(parents=True, exist_ok=True)
    (target / "spec.json").write_text(spec_json + "\n")
    (target / "run.py").write_text(
        RUN_TEMPLATE.format(slug=slug, kind=args.kind, spec_json=spec_json, prelude=PRELUDES[args.kind])
    )
    (target / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2) + "\n")
    print(target)
    try:
        push_path = target.relative_to(REPO)
    except ValueError:
        push_path = target
    print(f"push: uvx --from kaggle kaggle kernels push -p {push_path}")


if __name__ == "__main__":
    main()
