"""h-ghost-h1jax-room05b-e2-v6-replay25-lr5e5: h ghost h1jax cpt run. Generated by kaggle/spec_kernel.py; do not edit by hand.

The kernel is h1jax.kernels.cpt.main in the hghost_jax wheel (>= 0.2.0) attached through the code
dataset; this file installs the wheel and hands it the spec below (kept byte-identical in spec.json).
"""

import glob
import json
import os
import subprocess
import sys

SPEC = json.loads(r"""
{
  "kind": "cpt",
  "run_name": "room05b-e2-v6-replay25-lr5e5-decay10",
  "ssd": "v2",
  "per_chip": 16,
  "lr": 5e-05,
  "branch_from": "/kaggle/input/**/room05b-e1-decay10/tokens-000375783424/trainer_state.json",
  "total_tokens": 934331985,
  "decay_tokens": 55854856,
  "save_tokens": [878477129],
  "max_minutes": 150.0,
  "extra_validation": "room-validation.bin",
  "watchdog_minutes": 30.0
}
""")

LOCAL = os.environ.get("HGHOST_LOCAL") == "1" or SPEC.get("local") in (True, 1, "1")
if not LOCAL:
    wheels = [p for p in glob.glob("/kaggle/input/**/hghost_jax-*.whl", recursive=True) if os.path.isfile(p)]
    if len(wheels) != 1:
        raise RuntimeError(f"Expected exactly one hghost_jax wheel under /kaggle/input, found: {wheels}")
    subprocess.run([sys.executable, "-m", "pip", "install", "--no-deps", "--quiet", wheels[0]], check=True)
    print(json.dumps({"event": "wheel", "path": wheels[0]}), flush=True)
    os.environ.setdefault("JAX_COMPILATION_CACHE_DIR", "/kaggle/working/jax-cache")
# h1jax reads its SSD implementation and rematerialization policy from the environment at import.
os.environ.setdefault("H1JAX_SSD", str(SPEC.get("ssd", "v1")))
if SPEC.get("remat_policy"):
    os.environ.setdefault("H1JAX_REMAT_POLICY", str(SPEC["remat_policy"]))

from h1jax.kernels.cpt import main

main(SPEC)
